[package]
name = "twelf"
version = "0.1.0"
authors = ["Benjamin Coenen <5719034+bnjjj@users.noreply.github.com>"]
edition = "2018"
license = "MIT"
keywords = ["config", "configuration", "env", "environment", "settings"]
categories = ["config"]
readme = "README.md"
homepage = "https://github.com/bnjjj/twelf"
repository = "https://github.com/bnjjj/twelf"
description = "Twelf is a configuration solution for Rust including 12-Factor support. It is designed with layers in order to configure different sources and formats to build your configuration. The main goal is to be very simple using a proc macro."


[features]
default = ["json", "ini", "yaml", "clap", "toml", "dhall"]
ini = ["serde_ini"]
json = []
yaml = ["serde_yaml"]
toml = ["toml_rs"]
dhall = ["serde_dhall"]
clap = ["clap_rs"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
envy = { git = "https://github.com/bnjjj/envy", branch = "master" }
config-derive = { path = "../config-derive" }
serde_json = { version = "1.0.59" }
thiserror = "1.0.22"
log = "0.4.11"
serde = { version = "1.0.117", features = ["derive"] }

# Features
serde_ini = { version = "0.2.0", optional = true }
serde_yaml = { version = "0.8.14", optional = true }
serde_dhall = { version = "0.8.0", optional = true }
toml_rs = { version =  "0.5.7", package = "toml", optional = true }
clap_rs = { version = "2.33.3", package = "clap", optional = true }